language: node_js

node_js:
- "8.12.0"

install:
- npm i -g yarn && yarn

script: 'true'

before_script:
- yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  fqdn: mphone.vn
  local_dir: dist
  on:
    branch: shop
